[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 0
optimizer = true     # enable or disable the solc optimizer
optimizer_runs = 100000 # the number of optimizer runs
solc_version = '0.8.15'
fs_permissions = [{access = "write", path = "./bytecode/"}, {access = "read", path = "./scripts/env.json"}]
remappings = [
    "solmate/=lib/solmate/src/",
    "forge-std/=lib/forge-std/src/",
    "clones/=lib/clones-with-immutable-args/src",
]
ffi = true

[fuzz]
runs = 4096